# Generated by Django 5.0.6 on 2024-07-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpnj', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('descricao', models.TextField()),
                ('capa', models.ImageField(upload_to='foto_capa')),
                ('edital', models.FileField(upload_to='edital_pdf')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.empresa')),
            ],
        ),
    ]
